//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using DB.Query.Core.Annotations.Entity;
using DB.Query.Core.Entities;

namespace SIGN.Query.Models.PersistenceContext.Entities.SignCi
{

    [Table("AuditLogs")]
    public partial class AuditLogs : EntityBase
    {
        /// <summary>
        /// Propiedade mapeada para a definição de Id
        /// </summary>
        [PrimaryKey()]
        [RequiredColumn("Id")]
        public System.Guid Id { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de UserId
        /// </summary>
        [StringColumnLength("UserId", 100)]
        public string UserId { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Type
        /// </summary>
        [StringColumnLength("Type", 100)]
        public string Type { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de TableName
        /// </summary>
        [StringColumnLength("TableName", 100)]
        public string TableName { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de DateTime
        /// </summary>
        [RequiredColumn("DateTime")]
        public System.DateTime DateTime { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de OldValues
        /// </summary>
        public string OldValues { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de NewValues
        /// </summary>
        public string NewValues { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de AffectedColumns
        /// </summary>
        public string AffectedColumns { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de PrimaryKey
        /// </summary>
        public string PrimaryKey { get; set; }

        #region Custom Implementation
        // Declare your implementation here

        #endregion
        
    }
}
