//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DB.Query.Core.Annotations;
using DB.Query.Core.Annotations.Entity;
using DB.Query.Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;


namespace DB.Query.SignEst.Entities
{
    
    [Database("SignEst")]
    [Table("EstItens")]
    public partial class EstItens : EntityBase
    {
        /// <summary>
        /// Propiedade mapeada para a definição de Codigo_Empresa
        /// </summary>
        [PrimaryKey()]
        [RequiredColumn("Codigo_Empresa")]
        [ColumnAttribute("Codigo_Empresa")]
        public int CodigoEmpresa { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Codigo_Filial
        /// </summary>
        [PrimaryKey()]
        [RequiredColumn("Codigo_Filial")]
        [ColumnAttribute("Codigo_Filial")]
        public int CodigoFilial { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CodGrupo
        /// </summary>
        [StringColumnLength("CodGrupo", 2)]
        public string CodGrupo { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CodClassif
        /// </summary>
        [StringColumnLength("CodClassif", 6)]
        public string CodClassif { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Cod_Item
        /// </summary>
        [StringColumnLength("Cod_Item", 4)]
        [ColumnAttribute("Cod_Item")]
        public string CodItem { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Cod_Full
        /// </summary>
        [PrimaryKey()]
        [RequiredColumn("Cod_Full")]
        [StringColumnLength("Cod_Full", 12)]
        [ColumnAttribute("Cod_Full")]
        public string CodFull { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de ContaContabil
        /// </summary>
        [StringColumnLength("ContaContabil", 14)]
        public string ContaContabil { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CodLocal
        /// </summary>
        [StringColumnLength("CodLocal", 7)]
        public string CodLocal { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Descricao1
        /// </summary>
        [RequiredColumn("Descricao1")]
        [StringColumnLength("Descricao1", 50)]
        public string Descricao1 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Descricao2
        /// </summary>
        [StringColumnLength("Descricao2", 50)]
        public string Descricao2 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Descricao3
        /// </summary>
        [StringColumnLength("Descricao3", 100)]
        public string Descricao3 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CodUniMed
        /// </summary>
        [StringColumnLength("CodUniMed", 3)]
        public string CodUniMed { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Peso_Unit_Kg
        /// </summary>
        [ColumnAttribute("Peso_Unit_Kg")]
        public System.Nullable<decimal> PesoUnitKg { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Qtde_Liq_Prod_kg
        /// </summary>
        [ColumnAttribute("Qtde_Liq_Prod_kg")]
        public System.Nullable<decimal> QtdeLiqProdkg { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Fator_Acondicionamento
        /// </summary>
        [ColumnAttribute("Fator_Acondicionamento")]
        public System.Nullable<int> FatorAcondicionamento { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Classif_Fiscal
        /// </summary>
        [RequiredColumn("Classif_Fiscal")]
        [StringColumnLength("Classif_Fiscal", 10)]
        [ColumnAttribute("Classif_Fiscal")]
        public string ClassifFiscal { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Prateleira
        /// </summary>
        [StringColumnLength("Prateleira", 8)]
        public string Prateleira { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Prazo_Processamento
        /// </summary>
        [ColumnAttribute("Prazo_Processamento")]
        public short PrazoProcessamento { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Estq_Min
        /// </summary>
        [ColumnAttribute("Estq_Min")]
        public System.Nullable<decimal> EstqMin { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de DatUltSai
        /// </summary>
        public System.Nullable<System.DateTime> DatUltSai { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de ConsMed
        /// </summary>
        public System.Nullable<decimal> ConsMed { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de FatSeg
        /// </summary>
        public System.Nullable<decimal> FatSeg { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de PMBalnc
        /// </summary>
        public System.Nullable<decimal> PMBalnc { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de SldBalnc
        /// </summary>
        public System.Nullable<decimal> SldBalnc { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de DatBalanço
        /// </summary>
        public System.Nullable<System.DateTime> DatBalanço { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CustoMedCont
        /// </summary>
        public System.Nullable<decimal> CustoMedCont { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Qtd
        /// </summary>
        public System.Nullable<decimal> Qtd { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Empenho
        /// </summary>
        public System.Nullable<decimal> Empenho { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de RCMAuto
        /// </summary>
        [RequiredColumn("RCMAuto")]
        public bool RCMAuto { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CustoMedCont_01
        /// </summary>
        [ColumnAttribute("CustoMedCont_01")]
        public System.Nullable<decimal> CustoMedCont01 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Qtd_01
        /// </summary>
        [ColumnAttribute("Qtd_01")]
        public System.Nullable<decimal> Qtd01 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CustoMedCont_02
        /// </summary>
        [ColumnAttribute("CustoMedCont_02")]
        public System.Nullable<decimal> CustoMedCont02 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Qtd_02
        /// </summary>
        [ColumnAttribute("Qtd_02")]
        public System.Nullable<decimal> Qtd02 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CustoMedCont_03
        /// </summary>
        [ColumnAttribute("CustoMedCont_03")]
        public System.Nullable<decimal> CustoMedCont03 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Qtd_03
        /// </summary>
        [ColumnAttribute("Qtd_03")]
        public System.Nullable<decimal> Qtd03 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CustoMedCont_04
        /// </summary>
        [ColumnAttribute("CustoMedCont_04")]
        public System.Nullable<decimal> CustoMedCont04 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Qtd_04
        /// </summary>
        [ColumnAttribute("Qtd_04")]
        public System.Nullable<decimal> Qtd04 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CustoMedCont_05
        /// </summary>
        [ColumnAttribute("CustoMedCont_05")]
        public System.Nullable<decimal> CustoMedCont05 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Qtd_05
        /// </summary>
        [ColumnAttribute("Qtd_05")]
        public System.Nullable<decimal> Qtd05 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CustoMedCont_06
        /// </summary>
        [ColumnAttribute("CustoMedCont_06")]
        public System.Nullable<decimal> CustoMedCont06 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Qtd_06
        /// </summary>
        [ColumnAttribute("Qtd_06")]
        public System.Nullable<decimal> Qtd06 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CustoMedCont_07
        /// </summary>
        [ColumnAttribute("CustoMedCont_07")]
        public System.Nullable<decimal> CustoMedCont07 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Qtd_07
        /// </summary>
        [ColumnAttribute("Qtd_07")]
        public System.Nullable<decimal> Qtd07 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CustoMedCont_08
        /// </summary>
        [ColumnAttribute("CustoMedCont_08")]
        public System.Nullable<decimal> CustoMedCont08 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Qtd_08
        /// </summary>
        [ColumnAttribute("Qtd_08")]
        public System.Nullable<decimal> Qtd08 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CustoMedCont_09
        /// </summary>
        [ColumnAttribute("CustoMedCont_09")]
        public System.Nullable<decimal> CustoMedCont09 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Qtd_09
        /// </summary>
        [ColumnAttribute("Qtd_09")]
        public System.Nullable<decimal> Qtd09 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CustoMedCont_10
        /// </summary>
        [ColumnAttribute("CustoMedCont_10")]
        public System.Nullable<decimal> CustoMedCont10 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Qtd_10
        /// </summary>
        [ColumnAttribute("Qtd_10")]
        public System.Nullable<decimal> Qtd10 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CustoMedCont_11
        /// </summary>
        [ColumnAttribute("CustoMedCont_11")]
        public System.Nullable<decimal> CustoMedCont11 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Qtd_11
        /// </summary>
        [ColumnAttribute("Qtd_11")]
        public System.Nullable<decimal> Qtd11 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CustoMedCont_12
        /// </summary>
        [ColumnAttribute("CustoMedCont_12")]
        public System.Nullable<decimal> CustoMedCont12 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Qtd_12
        /// </summary>
        [ColumnAttribute("Qtd_12")]
        public System.Nullable<decimal> Qtd12 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Ativo
        /// </summary>
        [RequiredColumn("Ativo")]
        public bool Ativo { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Num_Seq
        /// </summary>
        [StringColumnLength("Num_Seq", 16)]
        [ColumnAttribute("Num_Seq")]
        public string NumSeq { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CodSOA
        /// </summary>
        [RequiredColumn("CodSOA")]
        public int CodSOA { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CodSIKA
        /// </summary>
        [RequiredColumn("CodSIKA")]
        public int CodSIKA { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Fator_Conversao_Lbs
        /// </summary>
        [ColumnAttribute("Fator_Conversao_Lbs")]
        public System.Nullable<decimal> FatorConversaoLbs { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Descricao1_Old
        /// </summary>
        [StringColumnLength("Descricao1_Old", 50)]
        [ColumnAttribute("Descricao1_Old")]
        public string Descricao1Old { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Descricao2_Old
        /// </summary>
        [StringColumnLength("Descricao2_Old", 50)]
        [ColumnAttribute("Descricao2_Old")]
        public string Descricao2Old { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Codigo_Setor
        /// </summary>
        [StringColumnLength("Codigo_Setor", 2)]
        [ColumnAttribute("Codigo_Setor")]
        public string CodigoSetor { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Endereco1
        /// </summary>
        public short Endereco1 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Endereco2
        /// </summary>
        public short Endereco2 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Endereco3
        /// </summary>
        public System.Nullable<int> Endereco3 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de M3_Lado1
        /// </summary>
        [ColumnAttribute("M3_Lado1")]
        public System.Nullable<decimal> M3Lado1 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de M3_Lado2
        /// </summary>
        [ColumnAttribute("M3_Lado2")]
        public System.Nullable<decimal> M3Lado2 { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de M3_Fixo
        /// </summary>
        [ColumnAttribute("M3_Fixo")]
        public System.Nullable<decimal> M3Fixo { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de ETAR
        /// </summary>
        [StringColumnLength("ETAR", 255)]
        public string ETAR { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de EX_sic_std_code
        /// </summary>
        [StringColumnLength("EX_sic_std_code", 12)]
        [ColumnAttribute("EX_sic_std_code")]
        public string EXsicstdcode { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de EX_productline_code
        /// </summary>
        [StringColumnLength("EX_productline_code", 10)]
        [ColumnAttribute("EX_productline_code")]
        public string EXproductlinecode { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de EX_productfamily_code
        /// </summary>
        [StringColumnLength("EX_productfamily_code", 10)]
        [ColumnAttribute("EX_productfamily_code")]
        public string EXproductfamilycode { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de EX_itemclass_code
        /// </summary>
        [StringColumnLength("EX_itemclass_code", 10)]
        [ColumnAttribute("EX_itemclass_code")]
        public string EXitemclasscode { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de EX_itemsize_code
        /// </summary>
        [StringColumnLength("EX_itemsize_code", 10)]
        [ColumnAttribute("EX_itemsize_code")]
        public string EXitemsizecode { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de EX_packing_code
        /// </summary>
        [StringColumnLength("EX_packing_code", 10)]
        [ColumnAttribute("EX_packing_code")]
        public string EXpackingcode { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Codigo_Servico
        /// </summary>
        [RequiredColumn("Codigo_Servico")]
        [ColumnAttribute("Codigo_Servico")]
        public int CodigoServico { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Codigo_Servico_Item
        /// </summary>
        [RequiredColumn("Codigo_Servico_Item")]
        [ColumnAttribute("Codigo_Servico_Item")]
        public int CodigoServicoItem { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Lote_Minimo_Compra
        /// </summary>
        [ColumnAttribute("Lote_Minimo_Compra")]
        public System.Nullable<int> LoteMinimoCompra { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Qtd_Frac
        /// </summary>
        [ColumnAttribute("Qtd_Frac")]
        public System.Nullable<bool> QtdFrac { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Leadtime
        /// </summary>
        public System.Nullable<int> Leadtime { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Lote
        /// </summary>
        public System.Nullable<int> Lote { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Escopo
        /// </summary>
        public System.Nullable<bool> Escopo { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Codigo_Suprix
        /// </summary>
        [StringColumnLength("Codigo_Suprix", 150)]
        [ColumnAttribute("Codigo_Suprix")]
        public string CodigoSuprix { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de COD_GRUPO_SPED
        /// </summary>
        [StringColumnLength("COD_GRUPO_SPED", 2)]
        [ColumnAttribute("COD_GRUPO_SPED")]
        public string CODGRUPOSPED { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CEST
        /// </summary>
        [StringColumnLength("CEST", 7)]
        public string CEST { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de obriga_Manutencao
        /// </summary>
        [ColumnAttribute("obriga_Manutencao")]
        public System.Nullable<bool> obrigaManutencao { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Tipo_Servico_REINF
        /// </summary>
        [StringColumnLength("Tipo_Servico_REINF", 12)]
        [ColumnAttribute("Tipo_Servico_REINF")]
        public string TipoServicoREINF { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Credita_Pis_Cofins
        /// </summary>
        [ColumnAttribute("Credita_Pis_Cofins")]
        public System.Nullable<bool> CreditaPisCofins { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CodNatRend
        /// </summary>
        [StringColumnLength("CodNatRend", 6)]
        public string CodNatRend { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de RcmAutoCalculoAlt
        /// </summary>
        public System.Nullable<bool> RcmAutoCalculoAlt { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de CategoriaFornecimentoItensId
        /// </summary>
        public System.Nullable<long> CategoriaFornecimentoItensId { get; set; }

        [Ignore]
        [ForeignKey(typeof(EstLocal))]
        public EstLocal EstLocal { get; set; }

        [Ignore]
        [ForeignKey(typeof(EstLocal))]
        private Expression<Func<EstLocal, bool>> WhereEstLocal => (EstLocal EstLocal) =>  EstLocal.Codigo_Empresa  ==  Codigo_Empresa &&  EstLocal.Codigo_Filial  ==  Codigo_Filial &&  EstLocal.Codigo  ==  CodLocal &&  EstLocal.Codigo  ==  CodLocal;

        [Ignore]
        [ForeignKey(typeof(EstUniMed))]
        public EstUniMed EstUniMed { get; set; }

        [Ignore]
        [ForeignKey(typeof(EstUniMed))]
        private Expression<Func<EstUniMed, bool>> WhereEstUniMed => (EstUniMed EstUniMed) =>  EstUniMed.Codigo_Empresa  ==  Codigo_Empresa &&  EstUniMed.Codigo_Filial  ==  Codigo_Filial &&  EstUniMed.Codigo  ==  CodUniMed &&  EstUniMed.Codigo  ==  CodUniMed;

        [Ignore]
        [ForeignKey(typeof(EstGrupo))]
        public EstGrupo EstGrupo { get; set; }

        [Ignore]
        [ForeignKey(typeof(EstGrupo))]
        private Expression<Func<EstGrupo, bool>> WhereEstGrupo => (EstGrupo EstGrupo) =>  EstGrupo.CodGrupo  ==  CodGrupo &&  EstGrupo.CodGrupo  ==  CodGrupo;

        [Ignore]
        [ForeignKey(typeof(EstClasFisc))]
        public EstClasFisc EstClasFisc { get; set; }

        [Ignore]
        [ForeignKey(typeof(EstClasFisc))]
        private Expression<Func<EstClasFisc, bool>> WhereEstClasFisc => (EstClasFisc EstClasFisc) =>  EstClasFisc.Classif_Fiscal  ==  Classif_Fiscal &&  EstClasFisc.Classif_Fiscal  ==  Classif_Fiscal;

        [Ignore]
        [ReferencedByForeignKey(typeof(EstEPIMOB))]
        public List<EstEPIMOB> EstEPIMOB { get; set; }

        [Ignore]
        [ReferencedByForeignKey(typeof(EstEPIMOB))]
        private Expression<Func<EstEPIMOB, bool>> WhereEstEPIMOB => (EstEPIMOB EstEPIMOB) =>  EstEPIMOB.Cod_Full == Cod_Full &&  EstEPIMOB.Codigo_Empresa == Codigo_Empresa &&  EstEPIMOB.Codigo_Filial == Codigo_Filial;

        [Ignore]
        [ReferencedByForeignKey(typeof(EstEPIMOBLOG))]
        public List<EstEPIMOBLOG> EstEPIMOBLOG { get; set; }

        [Ignore]
        [ReferencedByForeignKey(typeof(EstEPIMOBLOG))]
        private Expression<Func<EstEPIMOBLOG, bool>> WhereEstEPIMOBLOG => (EstEPIMOBLOG EstEPIMOBLOG) =>  EstEPIMOBLOG.Cod_Full == Cod_Full &&  EstEPIMOBLOG.Codigo_Empresa == Codigo_Empresa &&  EstEPIMOBLOG.Codigo_Filial == Codigo_Filial;

        [Ignore]
        [ReferencedByForeignKey(typeof(EstItensImport))]
        public List<EstItensImport> EstItensImport { get; set; }

        [Ignore]
        [ReferencedByForeignKey(typeof(EstItensImport))]
        private Expression<Func<EstItensImport, bool>> WhereEstItensImport => (EstItensImport EstItensImport) =>  EstItensImport.Cod_Full == Cod_Full &&  EstItensImport.Codigo_Empresa == Codigo_Empresa &&  EstItensImport.Codigo_Filial == Codigo_Filial;

        [Ignore]
        [ReferencedByForeignKey(typeof(EstItensRCM))]
        public List<EstItensRCM> EstItensRCM { get; set; }

        [Ignore]
        [ReferencedByForeignKey(typeof(EstItensRCM))]
        private Expression<Func<EstItensRCM, bool>> WhereEstItensRCM => (EstItensRCM EstItensRCM) =>  EstItensRCM.Cod_Full == Cod_Full &&  EstItensRCM.Codigo_Empresa == Codigo_Empresa &&  EstItensRCM.Codigo_Filial == Codigo_Filial;

        [Ignore]
        [ReferencedByForeignKey(typeof(EstItensRM))]
        public List<EstItensRM> EstItensRM { get; set; }

        [Ignore]
        [ReferencedByForeignKey(typeof(EstItensRM))]
        private Expression<Func<EstItensRM, bool>> WhereEstItensRM => (EstItensRM EstItensRM) =>  EstItensRM.Cod_Full == Cod_Full &&  EstItensRM.Codigo_Empresa == Codigo_Empresa &&  EstItensRM.Codigo_Filial == Codigo_Filial;

        [Ignore]
        [ReferencedByForeignKey(typeof(EstMovtosold))]
        public List<EstMovtosold> EstMovtosold { get; set; }

        [Ignore]
        [ReferencedByForeignKey(typeof(EstMovtosold))]
        private Expression<Func<EstMovtosold, bool>> WhereEstMovtosold => (EstMovtosold EstMovtosold) =>  EstMovtosold.Cod_Full == Cod_Full &&  EstMovtosold.Codigo_Empresa == Codigo_Empresa &&  EstMovtosold.Codigo_Filial == Codigo_Filial;

        [Ignore]
        [ReferencedByForeignKey(typeof(EstSaldos))]
        public List<EstSaldos> EstSaldos { get; set; }

        [Ignore]
        [ReferencedByForeignKey(typeof(EstSaldos))]
        private Expression<Func<EstSaldos, bool>> WhereEstSaldos => (EstSaldos EstSaldos) =>  EstSaldos.Cod_Full == Cod_Full &&  EstSaldos.Codigo_Empresa == Codigo_Empresa &&  EstSaldos.Codigo_Filial == Codigo_Filial;

        [Ignore]
        [ReferencedByForeignKey(typeof(EstSaldosSubLocal))]
        public List<EstSaldosSubLocal> EstSaldosSubLocal { get; set; }

        [Ignore]
        [ReferencedByForeignKey(typeof(EstSaldosSubLocal))]
        private Expression<Func<EstSaldosSubLocal, bool>> WhereEstSaldosSubLocal => (EstSaldosSubLocal EstSaldosSubLocal) =>  EstSaldosSubLocal.Cod_Full == Cod_Full &&  EstSaldosSubLocal.Codigo_Empresa == Codigo_Empresa &&  EstSaldosSubLocal.Codigo_Filial == Codigo_Filial;

        #region Custom Implementation
        // Declare your implementation here

        #endregion
        
    }
}
