//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DB.Query.Core.Annotations;
using DB.Query.Core.Annotations.Entity;
using DB.Query.Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;


namespace DB.Query.CommercialDb.Entities
{
    
    [Database("CommercialDb")]
    [Table("Product")]
    public partial class Product : EntityBase
    {
        /// <summary>
        /// Propiedade mapeada para a definição de ProductId
        /// </summary>
        [PrimaryKey(Identity=true)]
        [RequiredColumn("ProductId")]
        public int ProductId { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de ProductName
        /// </summary>
        [RequiredColumn("ProductName")]
        [StringColumnLength("ProductName", 255)]
        public string ProductName { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de ProductDescription
        /// </summary>
        [StringColumnLength("ProductDescription", 500)]
        public string ProductDescription { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de ProductPrice
        /// </summary>
        [RequiredColumn("ProductPrice")]
        public decimal ProductPrice { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de StockQuantity
        /// </summary>
        [RequiredColumn("StockQuantity")]
        public int StockQuantity { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de Category
        /// </summary>
        [StringColumnLength("Category", 255)]
        public string Category { get; set; }
        /// <summary>
        /// Propiedade mapeada para a definição de ProductCode
        /// </summary>
        [StringColumnLength("ProductCode", 50)]
        public string ProductCode { get; set; }

        #region Custom Implementation
        // Declare your implementation here

        #endregion
        
    }
}
